import { catchRuntimeError } from "./utils";

export const onChain = catchRuntimeError(async (context) => {});
